export const ApiRequestConstants = {
    SET_API_REQUEST_PENDING: 'SET_API_REQUEST_PENDING',
    SET_API_REQUEST_SUCCESS: 'SET_API_REQUEST_SUCCESS',
    SET_API_REQUEST_ERROR: 'SET_API_REQUEST_ERROR',
    RESET_API_REQUEST_STATUS: 'RESET_API_REQUEST_STATUS'
};