export const LoginConstants = {
    
    LOGIN_REQUEST: 'AUTHORISER_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'AUTHORISER_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'AUTHORISER_LOGIN_FAILURE',
    
    LOGOUT: 'AUTHORISER_LOGOUT',
};
