export const VisitorConstants = {
    
    ADD_NEW_VISITOR: 'ADD_NEW_VISITOR',
    UPLOAD_VISITOR_SIGNATURE: 'UPLOAD_VISITOR_SIGNATURE',
    FETCH_SIGNED_IN_VISITOR_LIST: 'FETCH_SIGNED_IN_VISITOR_LIST',  
    UPLOAD_VISITOR_DOC: 'UPLOAD_VISITOR_DOC',
    SIGNED_OUT_VISITOR: 'SIGNED_OUT_VISITOR',
    FETCH_SIGNED_OUT_VISITOR_LIST: 'FETCH_SIGNED_OUT_VISITOR_LIST',
};
